[project]
name = "tdop"
version = "0.1.0"
description = "TDOP"
readme = "README.md"
requires-python = ">=3.14"

[dependency-groups]
dev = ["inline-snapshot>=0.32.0", "pytest>=9.0.2", "ruff>=0.15.0", "ty>=0.0.17"]
